project:
  type: book
  output-dir: ../docs
  
book:
  title: "Open Scholarship Bootcamp 2025"
  author: ["Rick Gilmore", "Alaina Pearce"]
  chapters:
    - index.qmd
    - schedule.qmd
    - presenters.qmd
  repo-url: https://github.com/penn-state-open-science/bootcamp-2025/
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    number-sections: false
    date-modified: last-modified
    fontsize: 1.2em
    