project:
  type: book
  output-dir: ../docs
  
book:
  title: "Bootcamp 2025"
  author: ["Rick Gilmore", "Alaina Pearce"]
  chapters:
    - index.qmd
    - part: schedule.qmd
      chapters:
      - day-1.qmd
      - day-2.qmd
      - day-3.qmd
    - part: People
      chapters:
      - directors.qmd
      - program-committee.qmd
      - presenters.qmd
    - part: More
      chapters:
      - sessions.qmd
      - registration.qmd
      - resources.qmd
  repo-url: https://github.com/penn-state-open-science/bootcamp-2025/
  repo-actions: [edit, issue]
  repo-subdir: src

format:
  html:
    theme: cosmo
    number-sections: false
    date-modified: last-modified
    